export const baseData = [
   {
      code: "dzfwzy",
      icon: "",
      count: null,
      disabled: true,
      label: "党政服务资源",
      children: [
         {
            code: "d_1",
            icon: "",
            count: null,
            disabled: true,
            label: "镇（街）党（工）委",
         },
         {
            code: "d_2",
            icon: "",
            count: null,
            disabled: true,
            label: "党组织",
         },
         {
            code: "partyBranch",
            icon: "",
            count: null,
            disabled: true,
            label: "党支部",
         },
         {
            code: "partyGroup",
            icon: "",
            count: null,
            disabled: true,
            label: "党小组",
         },
         {
            code: "zhdj_street_down_party_school",
            icon: "",
            count: null,
            disabled: true,
            label: "镇街党校",
         },
         {
            code: "zhdj_party_server_team",
            icon: "",
            count: null,
            disabled: true,
            label: "党群服务队",
         },
         {
            code: "zhdj_party_service_center",
            icon: "",
            count: null,
            disabled: true,
            label: "党群服务中心",
         },
         {
            code: "zhdj_party_duty_area",
            icon: "",
            count: null,
            disabled: true,
            label: "党员责任区",
         },
         {
            code: "zhdj_party_server_station",
            icon: "",
            count: null,
            disabled: true,
            label: "党员服务驿站",
         },
         {
            code: "zhdj_party_member_edu_base",
            icon: "",
            count: null,
            disabled: true,
            label: "党员教育基地",
         },
         {
            code: "zzt_sjzwdt",
            icon: "",
            count: null,
            disabled: true,
            label: "市级综合服务大厅",
         },
         {
            code: "zzt_qjzwdt",
            icon: "",
            count: null,
            disabled: true,
            label: "区级综合服务大厅",
         },
         {
            code: "zzt_zjzwdt",
            icon: "",
            count: null,
            disabled: true,
            label: "镇街综合服务大厅",
         },
         {
            code: "zzt_zyfwdt",
            icon: "",
            count: null,
            disabled: true,
            label: "专业服务大厅",
         },
         {
            code: "zzt_zhytj",
            icon: "",
            count: null,
            disabled: true,
            label: "综合一体机",
         },
         {
            code: "zzt_yhyti",
            icon: "",
            count: null,
            disabled: true,
            label: "银行一体机",
         },
         {
            code: "redPosition",
            icon: "",
            count: null,
            disabled: true,
            label: "红色阵地",
         },
         {
            code: "good_news",
            icon: "",
            count: null,
            disabled: true,
            label: "喜讯",
         },
      ]
   },
   {
      code: "rkzy",
      icon: "",
      count: null,
      disabled: true,
      label: "人口资源",
      children: [
         {
            code: "rk_1",
            icon: "",
            count: null,
            disabled: true,
            label: "实有人口数",
         },
         {
            code: "rk_2",
            icon: "",
            count: null,
            disabled: true,
            label: "来穗人数",
         },
         {
            code: "rk_3",
            icon: "",
            count: null,
            disabled: true,
            label: "网格数",
         },
         {
            code: 'partyMember',
            icon: "",
            count: null,
            disabled: true,
            label: "党员",
         },
         {
            code: "rk_4",
            icon: "",
            count: null,
            disabled: true,
            label: "党支部书记",
         },
         {
            code: "rk_5",
            icon: "",
            count: null,
            disabled: true,
            label: "三人小组",
         },
         {
            code: "rk_6",
            icon: "",
            count: null,
            disabled: true,
            label: "警务人员",
         },
         {
            code: "rk_7",
            icon: "",
            count: null,
            disabled: true,
            label: "医疗人员",
         },
         {
            code: "grid_person",
            icon: "",
            count: null,
            disabled: true,
            label: "网格员",
         },
         {
            code: "rk_8",
            icon: "",
            count: null,
            disabled: true,
            label: "应急专家",
         },
         {
            code: "street_responders",
            icon: "",
            count: null,
            disabled: true,
            label: "街道应急人员",
         },
         {
            code: "city_drainage_armed_person",
            icon: "",
            count: null,
            disabled: true,
            label: "市排水公司布防人员表",
         },
         {
            code: "rk_9",
            icon: "",
            count: null,
            disabled: true,
            label: "救援队伍",
            children: [
               {
                  code: "three_proof_work_book",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "三防工作通讯录",
               },
               {
                  code: "professional_roster_work",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "专业抢险队名册",
               },
               {
                  code: "three_proof_social_forces",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "三防保障社会救援力量",
               },
               {
                  code: "hazardous_chemicals_team",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "危化品抢险队",
               },
            ]
         }
      ]
   },
   {
      code: "j_0",
      icon: "",
      count: null,
      disabled: true,
      label: "基础设施资源",
      children: [
         {
            code: "j_1",
            icon: "",
            count: null,
            disabled: true,
            label: "教育资源",
            children: [
               {
                  code: "school",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "学校",
               },
               {
                  code: "vocation_training_school",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "民办职业培训学校",
               },
               {
                  code: "j_1_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "中等职业教育学校",
               },
               {
                  code: "j_1_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "技工学院",
               },
               {
                  code: "j_1_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "特殊教育学校",
               }
            ]
         },
         {
            code: "j_2",
            icon: "",
            count: null,
            disabled: true,
            label: "医疗资源",
            children: [
               {
                  code: "j_2_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "公立二级医院",
               },
               {
                  code: "j_2_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "公立三级医院",
               },
               {
                  code: "j_2_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "哨点医院",
               },
               {
                  code: "j_2_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "120网络医院",
               },
               {
                  code: "j_2_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "120分站",
               },
               {
                  code: "j_2_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "救护车（执行）",
               },
               {
                  code: "j_2_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "救护车（待命）",
               },
               {
                  code: "j_2_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "采血点",
               },
               {
                  code: "j_2_9",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "公立社区卫生服务中心",
               },
               {
                  code: "j_2_10",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "长护机构",
               },
               {
                  code: "hospital",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "医疗机构",
               },
               {
                  code: "j_2_11",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "定点零售店",
               }
            ]
         },
         {
            code: "j_3",
            icon: "",
            count: null,
            disabled: true,
            label: "司法资源",
            children: [
               {
                  code: "j_3_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "公证机构",
               },
               {
                  code: "j_3_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "司法鉴定机构",
               },
               {
                  code: "j_3_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "调委会",
               },
               {
                  code: "j_3_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "律师事务所",
               }
            ]
         },
         {
            code: "j_4",
            icon: "",
            count: null,
            disabled: true,
            label: "交通资源",
            children: [
               {
                  code: "j_4_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "机场",
               },
               {
                  code: "j_4_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "港口口岸",
               },
               {
                  code: "j_4_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "火车站",
               },
               {
                  code: "j_4_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "高铁站",
               },
               {
                  code: "j_4_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "客运站",
               },
               {
                  code: "j_4_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地铁站",
               },
               {
                  code: "j_4_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "货运站",
               },
               {
                  code: "j_4_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "客运车",
               },
               {
                  code: "j_4_9",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "危运车",
               },
               {
                  code: "j_4_10",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "危险货运",
               },
               {
                  code: "j_4_11",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "危险车辆",
               },
               {
                  code: "j_4_12",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "公交车",
               },
               {
                  code: "j_4_13",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "出租车",
               },
               {
                  code: "j_4_14",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "网约车",
               },
               {
                  code: "j_4_15",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "客运班车",
               },
               {
                  code: "j_4_16",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "旅游包车",
               },
               {
                  code: "j_4_17",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "燃气运输车",
               },
               {
                  code: "j_4_18",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "规划重点工程",
               },
               {
                  code: "j_4_19",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "在建重点工程",
               },
               {
                  code: "j_4_20",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "三环十九射",
               },
               {
                  code: "gas_station",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "加油站",
               },
               {
                  code: "j_4_21",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "加气站",
               },
               {
                  code: "parking_area",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "停车场、地下车库",
               },
               {
                  code: "j_4_22",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "停车咪表",
               },
               {
                  code: "j_4_23",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "公交站亭",
               },
               {
                  code: "j_4_24",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "交通岗亭",
               },
               {
                  code: "j_4_25",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "交通涵洞",
               },
               {
                  code: "j_4_26",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "交通信号灯",
               },
               {
                  code: "j_4_27",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "交通信号设施",
               },
               {
                  code: "j_4_28",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地下通道",
               },
               {
                  code: "j_4_29",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "信息显示屏",
               },
               {
                  code: "j_4_30",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "户外电子屏",
               }
            ]
         },
         {
            code: "msfwzy",
            icon: "",
            count: null,
            disabled: true,
            label: "民生服务资源",
            children: [
               {
                  code: "j_5_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "家庭床位",
               },
               {
                  code: "j_5_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "福利机构",
               },
               {
                  code: "j_5_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "养老机构",
               },
               {
                  code: "j_5_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "图书馆",
               },
               {
                  code: "j_5_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "文化馆",
               },
               {
                  code: "j_5_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "4A级以上景区",
               },
               {
                  code: "parkland_hotel",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "酒店",
               },
               {
                  code: "j_5_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "精品民宿",
               },
               {
                  code: "j_5_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "城市公园",
               },
               {
                  code: "j_5_9",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "森林公园",
               },
               {
                  code: "j_5_10",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "自然保护区",
               },
               {
                  code: "j_5_11",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "湿地公园",
               },
               {
                  code: "j_5_12",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "绿道",
               },
               {
                  code: "sport_facility",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "体育设施",
               },
               {
                  code: "j_5_13",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "名木古树景点",
               },
               {
                  code: "j_5_14",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "分类宣传栏",
               },
               {
                  code: "j_5_15",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "分类公示牌",
               },
               {
                  code: "j_5_16",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "电梯",
               },
               {
                  code: "j_5_17",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "井盖",
               },
               {
                  code: "j_5_18",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "路灯",
               },
               {
                  code: "j_5_19",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地灯",
               },
               {
                  code: "j_5_20",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "公共厕所",
               },
               {
                  code: "j_5_21",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "垃圾箱",
               },
               {
                  code: "j_5_22",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "垃圾装运点",
               },
               {
                  code: "j_5_23",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "垃圾收集站",
               },
               {
                  code: "j_5_24",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "垃圾填埋场",
               },
               {
                  code: "j_5_25",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "生化处理厂",
               },
               {
                  code: "j_5_26",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "消纳场",
               },
               {
                  code: "j_5_27",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "智慧垃圾分类示范点",
               },
               {
                  code: "j_5_28",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "垃圾分类收集点",
               },
               {
                  code: "construction_site",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "在建工地",
               },
               {
                  code: "j_5_29",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "环卫停车场",
               },
               {
                  code: "j_5_30",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "洒水车加水点",
               },
               {
                  code: "j_5_31",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "环卫工具房",
               },
               {
                  code: "j_5_32",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "散乱污",
               },
               {
                  code: "j_5_33",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "码头",
               },
               {
                  code: "j_5_34",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "主干道卡口监控",
               },
               {
                  code: "j_5_35",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "资源热力厂（建成）",
               },
               {
                  code: "j_5_36",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "台风路径图",
               }
            ]
         },
         {
            code: "j_6",
            icon: "",
            count: null,
            disabled: true,
            label: "电力资源",
            children: [
               {
                  code: "j_6_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "充电桩",
               }, {
                  code: "j_6_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "营业厅",
               }, {
                  code: "j_6_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "高压线铁塔",
               }, {
                  code: "j_6_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "变压器",
               }, {
                  code: "j_6_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "监控电子眼",
               }, {
                  code: "j_6_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "通信交接箱",
               }, {
                  code: "j_6_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "通信立杆",
               }
            ]
         },
         {
            code: "j_7",
            icon: "",
            count: null,
            disabled: true,
            label: "水利资源",
            children: [
               {
                  code: "hydraulics",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "水利设施",
               },
               {
                  code: "j_7_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "流域",
               },
               {
                  code: "j_7_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "水系",
               },
               {
                  code: "j_7_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "动态水系",
               },
               {
                  code: "j_7_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "河流",
               },
               {
                  code: "j_7_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "水库",
               },
               {
                  code: "j_7_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "湖泊",
               },
               {
                  code: "j_7_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "河湖堤坝",
               },
               {
                  code: "j_7_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "水域护栏",
               },
               {
                  code: "j_7_9",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "护坡",
               },
               {
                  code: "j_7_10",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "泵站",
               },
               {
                  code: "j_7_11",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "管网",
               },
               {
                  code: "j_7_12",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "单元",
               },
               {
                  code: "j_7_13",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "排水户",
               },
               {
                  code: "j_7_14",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "污水厂",
               },
               {
                  code: "j_7_15",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "积水监测",
               },
               {
                  code: "j_7_16",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "正在巡河人数",
               },
               {
                  code: "j_7_17",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "市级河湖长",
               }
            ]
         },
         {
            code: "j_8",
            icon: "",
            count: null,
            disabled: true,
            label: "燃气资源",
            children: [
               {
                  code: "gas_agent_point",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "燃气站点（代理点）",
               },
               {
                  code: "j_8_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "液化气站",
               },
               {
                  code: "j_8_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "天然气门站",
               }
            ]
         },
         {
            code: "j_9",
            icon: "",
            count: null,
            disabled: true,
            label: "历史文化资源",
            children: [
               {
                  code: "j_9_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史城区",
               },
               {
                  code: "j_9_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史文化名镇",
               },
               {
                  code: "j_9_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史文化名村",
               },
               {
                  code: "j_9_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "传统村落",
               },
               {
                  code: "j_9_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史文化街区",
               },
               {
                  code: "j_9_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史风貌区",
               },
               {
                  code: "j_9_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史建筑（城区紫线）",
               },
               {
                  code: "j_9_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "文物保护单位",
               },
               {
                  code: "j_9_9",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "革命文物保护单位",
               },
               {
                  code: "j_9_10",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "名木古树",
               },
               {
                  code: "j_9_11",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "尚未核定公布的不可移动文物",
               },
               {
                  code: "j_9_12",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "骑楼街",
               },
               {
                  code: "j_9_13",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地下文物埋藏区",
               },
               {
                  code: "j_9_14",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "传统街巷（麻石巷）",
               },
               {
                  code: "j_9_15",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "传统风貌建筑",
               },
               {
                  code: "j_9_16",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "博物馆",
               },
               {
                  code: "red_relics",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "红色革命遗址",
               },
               {
                  code: "j_9_17",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "国家级文化保护单位",
               },
               {
                  code: "j_9_18",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地下文物埋藏区",
               },
               {
                  code: "historic",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "史迹",
               }
            ]
         },
         {
            code: "j_10",
            icon: "",
            count: null,
            disabled: true,
            label: "应急资源",
            children: [
               {
                  code: "j_10_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "救援物资",
               },
               {
                  code: "j_10_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "无人机",
               },
               {
                  code: "j_10_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "三防应急动员车",
               },
               {
                  code: "j_10_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "直升机取水点",
               },
               {
                  code: "j_10_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "直升机临时起降点",
               },
               {
                  code: "j_10_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "防火林带",
               },
               {
                  code: "j_10_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "林区道路",
               },
               {
                  code: "j_10_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "瞭望台",
               },
               {
                  code: "j_10_9",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "消防蓄水池",
               },
               {
                  code: "j_10_10",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "重点防护目标",
               },
               {
                  code: "j_10_11",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "治安岗亭",
               },
               {
                  code: "j_10_12",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "人防工事",
               },
               {
                  code: "retainning_wall",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "挡土墙",
               },
               {
                  code: "j_10_13",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "抢险点",
               },
               {
                  code: "emergency_shelter",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "紧急避难场所",
               },
               {
                  code: "three_proof_material_warehouse",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "三防物资仓库",
               },
               {
                  code: "three_proof_unit_book",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "三防成员单位通讯录",
               }
            ]
         },
         {
            code: "j_11",
            icon: "",
            count: null,
            disabled: true,
            label: "危险隐患点",
            children: [
               {
                  code: "j_11_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "盲道",
               },
               {
                  code: "j_11_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "户外广告",
               },
               {
                  code: "j_11_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "宣传栏",
               },
               {
                  code: "risk_tree",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "危树",
               },
               {
                  code: "risk_house",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "危房",
               },
               {
                  code: "wall_pee_off",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "外墙脱落",
               },
               {
                  code: "j_11_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "死畜禽收运点",
               },
               {
                  code: "j_11_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "危化品企业",
               },
               {
                  code: "j_11_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史地震",
               },
               {
                  code: "j_11_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "重大隐患企业",
               },
               {
                  code: "chemical_company",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "化工企业",
               },
               {
                  code: "j_11_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "风险隐患(五头一口)",
               },
               {
                  code: "j_11_9",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "火点信息",
               },
               {
                  code: "j_11_10",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "积水风险点",
               },
               {
                  code: "water_point",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "内涝点",
               },
               {
                  code: "j_11_11",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "易涝点",
               },
               {
                  code: "j_11_12",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "崩塌滑坡",
               },
               {
                  code: "j_11_13",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "岩溶地面塌陷",
               },
               {
                  code: "j_11_14",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "软土地面沉降",
               },
               {
                  code: "j_11_15",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "隐患点分布",
               },
               {
                  code: "j_11_16",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "灾害点分布",
               },
               {
                  code: "geology_dizaster",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地质灾害点",
               }
            ]
         },
      ]
   },
   {
      code: "z_0",
      icon: "",
      count: null,
      disabled: true,
      label: "自然资源",
      children: [
         {
            code: "z_1",
            icon: "",
            count: null,
            disabled: true,
            label: "城市7条线",
            children: [
               {
                  code: "dzt-redLine",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "红线（建设用地控制线）",
               },
               {
                  code: "dzt-greenLine",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "绿线（绿地范围控制线）",
               },
               {
                  code: "dzt-blueLine",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "蓝线（地表水控制线）",
               },
               {
                  code: "dzt-purpleLine",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "紫线（历史建筑控制线）",
               },
               {
                  code: "dzt-blackLine",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "黑线（高压线用地控制线）",
               },
               {
                  code: "dzt-yellowLine",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "黄线（城市基础设施用地控制线）",
               },
               {
                  code: "dzt-orangeLine",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "橙线（交通用地控制界）",
               },
            ]
         },
         {
            code: "z_2",
            icon: "",
            count: null,
            disabled: true,
            label: "土地资源",
            children: [
               {
                  code: "z_2_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "房屋",
               },
               {
                  code: "building",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "楼栋",
               },
               {
                  code: "unit_building",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "单位楼栋",
               },
               {
                  code: "z_2_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "重点功能片区",
               },
               {
                  code: "z_2_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "土地利用现状",
               },
               {
                  code: "z_2_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "土地储备",
               },
               {
                  code: "z_2_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "土地供应",
               },
               {
                  code: "z_2_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "耕地保有量",
               },
               {
                  code: "z_2_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地质专题图",
               },
               {
                  code: "z_2_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "历史城区土规",
               },
            ]
         },
         {
            code: "z_3",
            icon: "",
            count: null,
            disabled: true,
            label: "矿产资源",
            children: [
               {
                  code: "z_3_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "国家级绿色矿山",
               },
               {
                  code: "z_3_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "省级绿色矿山",
               },
               {
                  code: "z_3_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "持证矿山",
               },
               {
                  code: "z_3_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "固体矿产禁采区",
               },
            ]
         },
         {
            code: "z_4",
            icon: "",
            count: null,
            disabled: true,
            label: "海岛资源",
            children: [
               {
                  code: "z_4_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "海洋功能区划",
               },
               {
                  code: "z_4_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "大陆海岸线",
               },
               {
                  code: "z_4_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "有居民海岛",
               },
               {
                  code: "z_4_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "无居民海岛",
               },
            ]
         }
      ]
   },
   {
      code: "wl_0",
      icon: "",
      count: null,
      disabled: true,
      label: "物联感知资源",
      children: [
         {
            code: "wl_1",
            icon: "",
            count: null,
            disabled: true,
            label: "应急监测设备",
            children: [
               {
                  code: "wl_1_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "边坡监测点",
               },
               {
                  code: "wl_1_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "沉降监测点",
               },
               {
                  code: "wl_1_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "海洋观测站",
               },
               {
                  code: "wl_1_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "地震监测站",
               },
               {
                  code: "wl_1_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "广播点",
               },
            ]
         },
         {
            code: "wl_2",
            icon: "",
            count: null,
            disabled: true,
            label: "气象监测设备",
            children: [
               {
                  code: "wl_2_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "气象监测站",
               },
               {
                  code: "wl_2_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "空气质量监测站",
               },
               {
                  code: "wl_2_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "雨量监测站",
               },
            ]
         },
         {
            code: "wl_3",
            icon: "",
            count: null,
            disabled: true,
            label: "珠江潮位图 ",
         },
         {
            code: "wl_4",
            icon: "",
            count: null,
            disabled: true,
            label: "水位监测设备",
            children: [
               {
                  code: "wl_4_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "水库水文站",
               },
               {
                  code: "wl_4_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "河道水位站",
               },
               {
                  code: "wl_4_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "拦河坝水文站",
               },
               {
                  code: "wl_4_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "管网液位监测点",
               },
               {
                  code: "wl_4_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "堰闸水文站",
               },
            ]
         },
         {
            code: "wl_5",
            icon: "",
            count: null,
            disabled: true,
            label: "水质监测设备",
            children: [
               {
                  code: "wl_5_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "国考断面",
               },
               {
                  code: "wl_5_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "水源地水质监测点",
               },
               {
                  code: "wl_5_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "污水厂水质监测点",
               },
               {
                  code: "wl_5_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "管网水质监测点",
               },
            ]
         },
         {
            code: "sensor",
            icon: "",
            count: null,
            disabled: true,
            label: "传感器 ",
         },
         {
            code: "smoke_equipment",
            icon: "",
            count: null,
            disabled: true,
            label: "烟感器",
         },
         {
            code: "bracelet",
            icon: "",
            count: null,
            disabled: true,
            label: "手环 ",
         },
         {
            code: "wl_6",
            icon: "",
            count: null,
            disabled: true,
            label: "视频监控",
            children: [
               {
                  code: "wl_6_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "城管云",
               },
               {
                  code: "camera_ai",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "AI摄像头",
               },
            ]
         }
      ]
   },
   {
      code: "jy_0",
      icon: "",
      count: null,
      disabled: true,
      label: "经济贸易资源",
      children: [
         {
            code: "business",
            icon: "",
            count: null,
            disabled: true,
            label: "企业信息 ",
         },
         {
            code: "jy_1",
            icon: "",
            count: null,
            disabled: true,
            label: "百强企业",
            children: [
               {
                  code: "jy_1_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "农业龙头企业",
               },
               {
                  code: "jy_1_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "规上工业前百强企业",
               },
               {
                  code: "jy_1_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "规上服务业营收前百强企业",
               },
               {
                  code: "jy_1_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "批零业商品销售额前百强企业",
               },
            ]
         },
         {
            code: "jy_2",
            icon: "",
            count: null,
            disabled: true,
            label: "重点企业",
            children: [
               {
                  code: "jy_2_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "规上企业",
               },
            ]
         },
         {
            code: "jy_3",
            icon: "",
            count: null,
            disabled: true,
            label: "劳动关系和谐企业",
         },
         {
            code: "qzt_zdqk",
            icon: "",
            count: null,
            disabled: true,
            label: "重点区块",
         },
         {
            code: "qzt_xxcy",
            icon: "",
            count: null,
            disabled: true,
            label: "新兴产业企业",
         },
         {
            code: "qzt_zccy",
            icon: "",
            count: null,
            disabled: true,
            label: "支柱产业企业",
         },
         {
            code: "qzt_zdfhq",
            icon: "",
            count: null,
            disabled: true,
            label: "重点孵化器",
         },
         {
            code: "jy_4",
            icon: "",
            count: null,
            disabled: true,
            label: "重点产业",
            children: [
               {
                  code: "jy_4_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "汽车产业",
               },
               {
                  code: "jy_4_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "新材料产业",
               },
               {
                  code: "jy_4_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "超高清视频产业",
               },
               {
                  code: "jy_4_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "集成电路产业",
               },
               {
                  code: "jy_4_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "高端装备制造产业",
               },
               {
                  code: "jy_4_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "都市消费工业产业",
               },
               {
                  code: "jy_4_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "生物医药与高端医疗器械产业",
               },
               {
                  code: "jy_4_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "软件和信息服务产业",
               },
            ]
         },
         {
            code: "qzt_zdyq",
            icon: "",
            count: null,
            disabled: true,
            label: "重点园区",
         },
         {
            code: "jy_5",
            icon: "",
            count: null,
            disabled: true,
            label: "工业园",
            children: [
               {
                  code: "jy_5_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "工业产业区块分布图",
               },
               {
                  code: "jy_5_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "村级工业园分布图",
               },
            ]
         },
         {
            code: "jy_6",
            icon: "",
            count: null,
            disabled: true,
            label: "外贸金额热力图",
         },
      ]
   },
   {
      code: "ms_0",
      icon: "",
      count: null,
      disabled: true,
      label: "民生服务资源",
      children: [
         {
            code: "ms_1",
            icon: "",
            count: null,
            disabled: true,
            label: "事件",
            children: [
               {
                  code: "event",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "事件",
               },
               {
                  code: "ms_1_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "网格事件",
               },
               {
                  code: "ms_1_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "12345事件",
               },
               {
                  code: "ms_1_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "交通治理",
               },
               {
                  code: "ms_1_4",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "数字城管与综合执法",
               },
               {
                  code: "ms_1_5",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "生态执法",
               },
               {
                  code: "ms_1_6",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "巡河问题",
               },
               {
                  code: "ms_1_7",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "应急事故",
               },
               {
                  code: "ms_1_8",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "灾害预警",
               },
            ]
         },
         {
            code: "ms_2",
            icon: "",
            count: null,
            disabled: true,
            label: "应急示范社区",
         },
         {
            code: "ms_3",
            icon: "",
            count: null,
            disabled: true,
            label: "人口热力图",
         },
         {
            code: "ms_4",
            icon: "",
            count: null,
            disabled: true,
            label: "劳动就业热力图",
            children: [
               {
                  code: "ms_4_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "城镇新增就业人员",
               },
               {
                  code: "ms_4_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "异地务工人员",
               },
               {
                  code: "ms_4_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "失业人员",
               },
            ]
         },
         {
            code: "ms_5",
            icon: "",
            count: null,
            disabled: true,
            label: "住房公积金热力图",
            children: [
               {
                  code: "ms_5_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "住房贷款房屋均价",
               },
               {
                  code: "ms_5_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "住房贷款笔数",
               },
               {
                  code: "ms_5_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "实缴单位数",
               },
            ]
         },
         {
            code: "ms_6",
            icon: "",
            count: null,
            disabled: true,
            label: "社会保险分布图",
         },
         {
            code: "ms_7",
            icon: "",
            count: null,
            disabled: true,
            label: "房地产",
            children: [
               {
                  code: "ms_7_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "成交面积",
               },
               {
                  code: "ms_7_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "同比增长情况",
               },
            ]
         },
         {
            code: "ms_8",
            icon: "",
            count: null,
            disabled: true,
            label: "医疗保障",
            children: [
               {
                  code: "ms_8_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "长护机构",
               },
               {
                  code: "ms_8_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "定点医疗机构",
               },
               {
                  code: "ms_8_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "定点零售店",
               },
            ]
         },
         {
            code: "ms_9",
            icon: "",
            count: null,
            disabled: true,
            label: "空气质量",
            children: [
               {
                  code: "ms_9_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "空气质量预报",
               },
               {
                  code: "ms_9_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "重点排污单位（气、水）",
               },
            ]
         },
         {
            code: "ms_10",
            icon: "",
            count: null,
            disabled: true,
            label: "水环境质量",
            children: [
               {
                  code: "ms_10_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "排水单元",
               },
               {
                  code: "ms_10_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "排水户",
               },
               {
                  code: "ms_10_3",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "考核断面",
               },
            ]
         },
         {
            code: "ms_11",
            icon: "",
            count: null,
            disabled: true,
            label: "农业气象指数保险",
         },
         {
            code: "ms_12",
            icon: "",
            count: null,
            disabled: true,
            label: "固废污染防治",
            children: [
               {
                  code: "ms_12_1",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "一般工业固体废物企业数（家）",
               },
               {
                  code: "ms_12_2",
                  icon: "",
                  count: null,
                  disabled: true,
                  label: "处理处置设施",
               },
            ]
         },
      ]
   }
]


