export const commonData = [
   {
      code:'1',
      icon:'',
      count:null,
      label:'地',
      children:[
         {
            code:'11',
            icon:'',
            count:null,
            label:'城市7条线',
            children:[
               {
                  code:'dzt-redLine',
                  icon:require('@/assets/szg_land/cluster/dzt-redLine.png'),
                  count:null,
                  label:'红线（建设用地控制线）',
               },
               {
                  code:'dzt-greenLine',
                  icon:require('@/assets/szg_land/cluster/dzt-greenLine.png'),
                  count:null,
                  label:'绿线（绿地范围控制线）',
               },
               {
                  code:'dzt-blueLine',
                  icon:require('@/assets/szg_land/cluster/dzt-blueLine.png'),
                  count:null,
                  label:'蓝线（地表水控制线）',
               },
               {
                  code:'dzt-purpleLine',
                  icon:require('@/assets/szg_land/cluster/dzt-purpleLine.png'),
                  count:null,
                  label:'紫线（历史建筑控制线）',
               },
               {
                  code:'dzt-blackLine',
                  icon:require('@/assets/szg_land/cluster/dzt-blackLine.png'),
                  count:null,
                  label:'黑线（高压线用地控制线）',
               },
               {
                  code:'dzt-yellowLine',
                  icon:require('@/assets/szg_land/cluster/dzt-yellowLine.png'),
                  count:null,
                  label:'黄线（城市基础设施用地控制线）',
               },
               {
                  code:'dzt-orangeLine',
                  icon:require('@/assets/szg_land/cluster/dzt-orangeLine.png'),
                  count:null,
                  label:'橙线（交通用地控制界）',
               },
            ]
         },
         {
            code:'building',
            icon:'',
            count:null,
            label:'楼栋',
         }
      ]
   },
   {
      code:'2',
      icon:'',
      count:null,
      label:'人',
      children:[
         {
            code:'partyMember',
            icon:'',
            count:null,
            label:'党员',
         }, {
            code:'grid_person',
            icon:'',
            count:null,
            label:'网格员',
         }, {
            code:'street_responders',
            icon:'',
            count:null,
            label:'街道应急人员',
         },	{
            code:'24',
            icon:'',
            count:null,
            label:'救援队伍',
            children:[
               {
                  code:'three_proof_work_book',
                  icon:'',
                  count:null,
                  label:'三防工作通讯录',
               },{
                  code:'three_proof_social_forces',
                  icon:'',
                  count:null,
                  label:'三防保障社会救援力量',
               },{
                  code:'professional_roster_work',
                  icon:'',
                  count:null,
                  label:'专业抢险队名册',
               },{
                  code:'hazardous_chemicals_team',
                  icon:'',
                  count:null,
                  label:'危化品抢险队',
               },
            ]
         },
      ]
   },
   {
      code:'3',
      icon:'',
      count:null,
      label:'企',
      children:[
         {
            code:'business',
            icon:'',
            count:null,
            label:'企业基本信息',
         },	{
            code:'qzt_zccy',
            icon:'',
            count:null,
            label:'支柱产业企业',
         },	{
            code:'qzt_xxcy',
            icon:'',
            count:null,
            label:'新兴产业企业',
         },	{
            code:'qzt_zdqk',
            icon:'',
            count:null,
            label:'重点区块',
         },
      ]
   },
   {
      code:'4',
      icon:'',
      count:null,
      label:'物',
      children:[
         {
            code:'sensor',
            icon:'',
            count:null,
            label:'传感器',
         },
         {
            code:'42',
            icon:'',
            count:null,
            label:'教育资源',
            children:[
               {
                  code:'school',
                  icon:'',
                  count:null,
                  label:'学校',
               },{
                  code:'vocation_training_school',
                  icon:'',
                  count:null,
                  label:'民办职业培训学校',
               },
            ]
         },
         {
            code:'43',
            icon:'',
            count:null,
            label:'交通资源',
            children:[
               {
                  code:'gas_station',
                  icon:'',
                  count:null,
                  label:'加油站',
               },{
                  code:'parking_area',
                  icon:'',
                  count:null,
                  label:'停车场、地下车库',
               },
            ]
         },
         {
            code:'44',
            icon:'',
            count:null,
            label:'民生资源',
            children:[
               {
                  code:'parkland_hotel',
                  icon:'',
                  count:null,
                  label:'酒店',
               },{
                  code:'sport_facility',
                  icon:'',
                  count:null,
                  label:'体育设施',
               },
            ]
         },
         {
            code:'hydraulics',
            icon:'',
            count:null,
            label:'水利设施',
         },
         {
            code:'gas_agent_point',
            icon:'',
            count:null,
            label:'燃气站点（代理点）',
         },
         {
            code:'47',
            icon:'',
            count:null,
            label:'历史文化资源',
            children:[
               {
                  code:'red_relics',
                  icon:'',
                  count:null,
                  label:'红色革命遗址',
               },
            ]
         },
         {
            code:'48',
            icon:'',
            count:null,
            label:'应急资源',
            children:[
               {
                  code:'emergency_shelter',
                  icon:'',
                  count:null,
                  label:'避难场所',
               },{
                  code:'three_proof_material_warehouse',
                  icon:'',
                  count:null,
                  label:'三防物资仓库',
               },
            ]
         },
         {
            code:'49',
            icon:'',
            count:null,
            label:'风险隐患点',
            children:[
               {
                  code:'risk_tree',
                  icon:'',
                  count:null,
                  label:'危树',
               },{
                  code:'risk_house',
                  icon:'',
                  count:null,
                  label:'危房',
               }, {
                  code:'wall_pee_off',
                  icon:'',
                  count:null,
                  label:'外墙脱落',
               },{
                  code:'chemical_company',
                  icon:'',
                  count:null,
                  label:'化工企业',
               },{
                  code:'water_point',
                  icon:'',
                  count:null,
                  label:'内涝点',
               },
            ]
         },
      ]
   },
   {
      code:'5',
      icon:'',
      count:null,
      label:'政',
      children:[
         {
            code:'partyBranch',
            icon:'',
            count:null,
            label:'党支部',
         },	{
            code:'partyGroup',
            icon:'',
            count:null,
            label:'党小组',
         },	{
            code:'zhdj_street_down_party_school',
            icon:'',
            count:null,
            label:'镇街党校',
         },	{
            code:'zhdj_party_server_team',
            icon:'',
            count:null,
            label:'党群服务队',
         },{
            code:'zhdj_party_service_center',
            icon:'',
            count:null,
            label:'党群服务中心',
         },	{
            code:'zhdj_party_member_edu_base',
            icon:'',
            count:null,
            label:'党员教育基地',
         },
         {
            code:'57',
            icon:'',
            count:null,
            label:'政务大厅',
            children:[
               {
                  code:'zzt_sjzwdt',
                  icon:'',
                  count:null,
                  label:'市级综合服务大厅',
               },
               {
                  code:'zzt_qjzwdt',
                  icon:'',
                  count:null,
                  label:'区级综合服务大厅',
               },
               {
                  code:'zzt_zjzwdt',
                  icon:'',
                  count:null,
                  label:'镇街综合服务大厅',
               },
               {
                  code:'zzt_zyfwdt',
                  icon:'',
                  count:null,
                  label:'专业服务大厅',
               },
            ]
         },
         {
            code:'58',
            icon:'',
            count:null,
            label:'一体机',
            children:[
               {
                  code:'zzt_zhytj',
                  icon:'',
                  count:null,
                  label:'综合一体机',
               },{
                  code:'zzt_yhyti',
                  icon:'',
                  count:null,
                  label:'银行一体机',
               },
            ]
         }, {
            code:'zzt_zwxw',
            icon:'',
            count:null,
            label:'政务小屋',
         }, {
            code:'zzt_zwy',
            icon:'',
            count:null,
            label:'政务云',
         }, {
            code:'zzt_zww',
            icon:'',
            count:null,
            label:'政务网',
         },
      ]
   },
]